vcsutils/webhookparser/bitbucketcloud.go, vcsutils/webhookparser/bitbucketcloud_test.go, vcsutils/webhookparser/bitbucketserver.go, vcsutils/webhookparser/bitbucketserver_test.go, vcsutils/webhookparser/common_test.go, vcsutils/webhookparser/github.go, vcsutils/webhookparser/github_test.go, vcsutils/webhookparser/gitlab.go, vcsutils/webhookparser/gitlab_test.go, vcsutils/webhookparser/webhookparser.go
This returns the repo owner and name as distinct field, and also fixes some inconsistencies with GetRepositories where we would return the slug and the webhook would return the name
=> set repo/owner in different fields for webhookinfo

vcsclient/bitbucketcloud_test.go, vcsclient/bitbucketserver_test.go, vcsclient/github_test.go, vcsclient/gitlab.go, vcsclient/gitlab_test.go
=> Fix get latest commit for gitlab returns empty

vcsutils/webhookparser/gitlab.go
GitLab provider panics if push event has no Commits
provided. Fix it by checking presents of at least one
commit object before getting a timestamp.
- [-] This feature is included on all supported VCS providers - GitHub, Bitbucket cloud, Bitbucket server, and GitLab.
---
Closes: https://github.com/jfrog/froggit-go/issues/30
=> 30 - panic if push has no commits

README.md, vcsclient/bitbucketcloud.go, vcsclient/bitbucketcloud_test.go, vcsclient/bitbucketcommon.go, vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go, vcsclient/common_test.go, vcsclient/github.go, vcsclient/github_test.go, vcsclient/gitlab.go, vcsclient/gitlab_test.go, vcsclient/vcsclient.go
---
Add labels APIs for GitHub and GitLab.
Currently, labels in Bitbucket are not supported: https://jira.atlassian.com/browse/BSERV-10715
=> Support labels API

README.md, vcsclient/bitbucketcloud.go, vcsclient/bitbucketcloud_test.go, vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go, vcsclient/github.go, vcsclient/github_test.go, vcsclient/gitlab.go, vcsclient/gitlab_test.go, vcsclient/validate_required_params_test.go, vcsclient/vcsclient.go
---
Supersede https://github.com/jfrog/froggit-go/pull/34
=> Support add comment API

vcsclient/github.go, vcsclient/github_test.go
---
Issue Description -
Github list repositories API does not iterate through all the pages available in the remote repository. And it also repeats the repository names when there is more than one page.
Fix Details -
The problem here is that the page index variable in the library is initialized as zero, so the first-page request goes as https://api.github.com/user/repos?page=0 followed by https://api.github.com/user/repos?page=1. Both these requests are treated as a request for Page 1 by the GitHub API, and will return the same result set.
=> Fix for pagination issues in Gitlab list repositories.

go.mod, go.sum, vcsclient/bitbucketcloud.go, vcsclient/bitbucketcloud_test.go, vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go, vcsclient/github.go, vcsclient/github_test.go, vcsclient/gitlab.go, vcsclient/gitlab_test.go, vcsclient/testdata/bitbucketcloud/pull_request_comments_list_response.json, vcsclient/testdata/bitbucketserver/pull_request_comments_list_response.json, vcsclient/testdata/github/pull_request_comments_list_response.json, vcsclient/testdata/gitlab/pull_request_comments_list_response.json, vcsclient/vcsclient.go
=> New ListPullRequestComments API

vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go
=> Bug fix: download repository branch from bitbucket server

vcsclient/github.go, vcsclient/github_test.go, vcsclient/testdata/github/pull_requests_list_response.json
---
- Used in Frogbot's scan-pull-requests when using GitHub with Jenkins.
=> Fix Github ListOpenPullRequests

vcsclient/azurerepos.go, vcsclient/bitbucketcloud.go, vcsclient/github.go, vcsutils/utils.go, vcsutils/utils_test.go
=> Check HTTP response status code in DownloadRepository

vcsutils/utils.go, vcsutils/utils_test.go
=> Skip CreateDotGitFolderWithRemote if .git exists

README.md, vcsclient/azurerepos.go, vcsclient/azurerepos_test.go, vcsclient/bitbucketcloud.go, vcsclient/bitbucketcloud_test.go, vcsclient/bitbucketcommon.go, vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go, vcsclient/github.go, vcsclient/github_test.go, vcsclient/gitlab.go, vcsclient/gitlab_test.go, vcsclient/vcsclient.go
=> Add DownloadFileFromRepo API to GitHub and GitLab

vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go, vcsclient/github.go, vcsclient/gitlab.go
=> Added DownloadFileFromRepository to Bitbucket Server

vcsclient/bitbucketcloud.go, vcsclient/bitbucketcloud_test.go, vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go, vcsclient/common_test.go, vcsclient/github.go, vcsclient/github_test.go, vcsclient/gitlab.go, vcsclient/gitlab_test.go, vcsclient/vcsclient.go
=> Add repository visibility to the repository info

README.md, vcsclient/azurerepos.go, vcsclient/azurerepos_test.go, vcsclient/bitbucketcloud.go, vcsclient/bitbucketcloud_test.go, vcsclient/bitbucketcommon.go, vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go, vcsclient/common_test.go, vcsclient/github.go, vcsclient/github_test.go, vcsclient/gitlab.go, vcsclient/gitlab_test.go, vcsclient/gitlabcommon.go, vcsclient/testdata/github/repository_environment_response.json, vcsclient/vcsclient.go
=> New Get Repository Environment Info API

README.md, go.mod, go.sum, vcsclient/azurerepos.go, vcsclient/azurerepos_test.go, vcsclient/bitbucketcloud.go, vcsclient/bitbucketcloud_test.go, vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go, vcsclient/github.go, vcsclient/github_test.go, vcsclient/gitlab.go, vcsclient/gitlab_test.go, vcsclient/testdata/azurerepos/compare_commits.json, vcsclient/testdata/azurerepos/resourcesResponse.json, vcsclient/testdata/bitbucketcloud/compare_commits.json, vcsclient/testdata/bitbucketserver/compare_commits.json, vcsclient/testdata/github/compare_commits.json, vcsclient/testdata/gitlab/compare_commits.json, vcsclient/vcsclient.go, vcsutils/utils.go, vcsutils/utils_test.go
---
A new method GetModifiedFiles is added. It returns paths of the files modified between two references (tags, commits, branches) using 3-dot diff range flow.
It is needed by the https://jfrog-int.atlassian.net/browse/INTG-389
=> Add GetModifiedFiles

vcsclient/gitlab.go, vcsclient/gitlab_test.go
=> Add .git initialization on DownloadRepository for GitLab

vcsclient/bitbucketcloud.go, vcsclient/bitbucketcloud_test.go, vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go
=> Bitbucket - get modified files for commits (fix order of parameters)

vcsclient/azurerepos.go, vcsclient/bitbucketcloud.go, vcsclient/bitbucketserver.go, vcsutils/utils.go, vcsutils/utils_test.go, vcsutils/webhookparser/bitbucketcloud.go, vcsutils/webhookparser/bitbucketcloud_test.go, vcsutils/webhookparser/bitbucketserver.go, vcsutils/webhookparser/bitbucketserver_test.go, vcsutils/webhookparser/github.go, vcsutils/webhookparser/github_test.go, vcsutils/webhookparser/gitlab.go, vcsutils/webhookparser/gitlab_test.go, vcsutils/webhookparser/webhookparser.go
---
The change extends `WebhookInfo` with additional information about Pull request. 
The new field `PullRequest` encapsulates information about pull request, like source and destination, title, etc...
It has fields that duplicate existing one, but it is done intentionally as the current structure is hard to understand and maintain. The old fields will be removed eventually.
The change is needed for https://jfrog-int.atlassian.net/browse/INTG-386.
=> Extend WebhookInfo with additional information about Pull Requests

vcsclient/azurerepos.go, vcsclient/bitbucketcloud.go, vcsclient/bitbucketcommon.go, vcsclient/bitbucketcommon_test.go, vcsclient/bitbucketserver.go, vcsclient/github.go, vcsclient/gitlab.go, vcsclient/vcsclient.go
---
Parsing `createdOn` and `updatedOn` values of a commit status failed due to a wrong response parsing. 
The Bitbucket server scheme is as follows:
```
{
"size": 1,
"limit": 25,
"isLastPage": true,
"values": [
{
"state": "SUCCESSFUL",
"key": "REPO-MASTER",
"name": "REPO-MASTER-42",
"url": "https://bamboo.example.com/browse/REPO-MASTER-42",
"description": "Changes by John Doe",
"dateAdded": 1442835514204
}
],
"start": 0
}
```
The Bitbucket Cloud is as follows:
```
...
"created_on": "<string>",
"updated_on": "<string>"
```
In the case of Bitbucket Server, we'll parse the `dateAdded` field, on Bitbucket Cloud we'll parse the `created_on` and `updated_on` fields.
=> Fix Bitbucket GetCommitStatus date parsing

vcsclient/azurerepos.go
---
There was a bug in getting and setting commit statuses in azure repos.
There was a mismatch between the project name and the repo name.
=> Fix Azure DevOps commit statuses functions

vcsclient/bitbucketserver.go
=> Fix wrong status code in Bitbucket Server DownloadRepository API

vcsclient/github.go, vcsclient/github_test.go, vcsutils/utils_test.go
---
**Bug description:**
When downloading a repo from GitHub cloud, the ApiEndpoint was set to `api.github.com`
and it was used to set the remote urls as well as `https://api.github.com/my-org/my-repo.git`
this is wrong as the remote url should be the GitHub host url which is `https://github.com/my-org/my-repo.git`
Bitbucket server & cloud is working correctly.
GitLab on perm & cloud is also working correctly.
=> Fix GitHub cloud remote URLs

vcsclient/bitbucketcloud.go, vcsclient/bitbucketcloud_test.go, vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go, vcsclient/github.go, vcsclient/github_test.go, vcsclient/gitlab.go, vcsclient/gitlab_test.go
If vcsutils.TagPushed or vcsutils.TagRemoved event type is provided the newly created webhook will receive tag related events.
---
=> Allow to listen for tag webhook events

vcsclient/gitlab.go, vcsclient/gitlab_test.go, vcsclient/testdata/gitlab/pull_requests_list_response.json
Correct the `state` parameter from `open` which causes gitlab to return the error `{"error":"state does not have a valid value"}` to `opened`.
`opened` matches the [Gitlab API specification](https://docs.gitlab.com/ee/api/merge_requests.html) where the `state` can only be `opened`, `closed`, `locked`, `merged` or `all`
=> Fix GitLab pull request state parameter

go.mod, go.sum, vcsclient/azurerepos.go, vcsclient/azurerepos_test.go, vcsclient/bitbucketcloud.go, vcsclient/bitbucketcloud_test.go, vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go, vcsclient/github.go, vcsclient/github_test.go, vcsclient/gitlab.go, vcsclient/gitlab_test.go, vcsclient/logger.go, vcsclient/testdata/azurerepos/resourcesResponse.json, vcsclient/vcsclient.go, vcsutils/consts.go, vcsutils/utils.go, vcsutils/utils_test.go
---
Adds the ability to update pull request's metadata
=> Add the ability to update pull requests metadata

vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go, vcsclient/testdata/bitbucketserver/pull_requests_list_response.json
---
Unify the response format of the function ListOpenPullRequest.
Returning only branch name as the ID in all VCS providers.
In Bitbucket Server it used to return with ref/head/branchName.
=> Standardize ListOpenPullRequest responses

vcsclient/azurerepos.go, vcsclient/azurerepos_test.go, vcsclient/bitbucketcloud.go, vcsclient/bitbucketcloud_test.go, vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go, vcsclient/github.go, vcsclient/github_test.go, vcsclient/gitlab.go, vcsclient/gitlab_test.go, vcsclient/logger.go, vcsclient/testdata/bitbucketcloud/get_pull_request_response.json, vcsclient/testdata/bitbucketserver/get_pull_request_response.json, vcsclient/testdata/bitbucketserver/get_pull_request_response_nil.json, vcsclient/testdata/github/pull_request_info_response.json, vcsclient/testdata/github/pull_requests_list_response.json, vcsclient/vcsclient.go, vcsutils/utils.go, vcsutils/utils_test.go
---
Add owner attribute to branch info, when getting pull request info it is important to know both of the owners, as they can differ when the pull request is from a forked repository.
=> Add owner attribute to BranchInfo

vcsclient/azurerepos.go, vcsclient/azurerepos_test.go
---
- When fetching the pull request details, we removed all the keywords with slashes from the branch names, instead of only removing the prefixes within the Git 'refs' namespace.
- Fixes https://github.com/jfrog/frogbot/issues/446
=> Fix wrong pull request branch parsing in Azure

vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go
---
For BitBucket, return the actual URL of the commit instead of the rest API URL for this commit
=> Fix BitBucket CommitInfo Url

vcsclient/gitlab.go
---
- Updated the close merge request value in UpdatePullRequest to "close" instead of "closed".
=> GitLab - Corrected "Closed" status value in UpdatePullRequest

vcsclient/azurerepos.go, vcsclient/bitbucketcloud.go, vcsclient/bitbucketcommon.go, vcsclient/bitbucketserver.go, vcsclient/github.go, vcsclient/gitlab.go, vcsclient/gitlabcommon.go, vcsclient/vcsclient.go
---
Add new methods to get the size limitations for the pull request content (details/comments).
It allows us to figure out dynamically if the content will overflow and the API will result in failures.
* Size limitation: `65,536` chars
Limitation is not mentioned in the docs, found references at: https://github.com/orgs/community/discussions/27190
* Merge Request details limit: `1,048,576` chars [docs](https://docs.gitlab.com/ee/api/merge_requests.html#create-mr)
* Merge Request comment content limit: `1,000,000` chars [docs](https://docs.gitlab.com/ee/api/notes.html#create-new-merge-request-note)
* Pull Request content limit: `32,768` chars:
```
11:07:00 [Error] couldn't add pull request comment: Status: 400 Bad Request, Body: {"errors":[{"context":"text","message":"Please enter a …
```
=> Get method for size limitation on PR content

vcsclient/azurerepos.go, vcsclient/azurerepos_test.go, vcsclient/bitbucketcloud.go, vcsclient/bitbucketcloud_test.go, vcsclient/bitbucketserver.go, vcsclient/bitbucketserver_test.go, vcsclient/github.go, vcsclient/github_test.go, vcsclient/gitlab.go, vcsclient/gitlab_test.go, vcsclient/vcsclient.go
---
Adding 'Title' attribute to the response that returns when asking to get a PR/MR info
=> Add 'Title' attribute to PR information

vcsclient/github.go, vcsclient/github_test.go, vcsclient/vcsclient.go
Add pull request status to Github GetPullRequestByID response:
---
Add pull request status to Github `GetPullRequestByID` response
=> Add pull request status to Github GetPullRequestByID response

vcsclient/azurerepos.go
---
This PR is aiming to fix the following issue: 
In Azure Devops, in case there is a branch name that includes special character (for example: étab), there is an error when trying to download the repository (in sendDownloadRepoRequest()): "<Branch: {branch_name} > could not be resolved"
The fix: adding escaping to the branch name string, so it can be safely placed in the download URL.
=>  Adding escaping to the branch name string in the download URL

vcsclient/github.go, vcsclient/github_test.go
---
This PR adds the missed 'Relationship' field to the handler's convertor and improves current API implementation
=> Fix dependency submission api convertor
