jfrog/froggit-go

- vcsclient/bitbucketcloud.go
Resolves #3 
Instead of setting the Bitbucket cloud base URL by an environment variable, set the URL after the creation of the client. This attitude should be thread safe.
> Set base URL differently in Bitbucket cloud

- .github/workflows/test.yml
- README.md
Send code coverage to coverall and generate a readme badge.
> Add code coverage

- vcsclient/bitbucketcommon_test.go
- vcsclient/bitbucketserver_test.go
- vcsclient/factory_test.go
- vcsclient/github.go
- vcsclient/github_test.go
- vcsclient/gitlab_test.go
- vcsutils/consts_test.go
- vcsutils/utils_test.go
- vcsutils/webhookparser/bitbucketcloud_test.go
- vcsutils/webhookparser/bitbucketserver_test.go
- vcsutils/webhookparser/factory_test.go
- vcsutils/webhookparser/github_test.go
- vcsutils/webhookparser/gitlab_test.go
Improve test coverage from 82.71% to 89.4%
> Add more tests

- .github/workflows/test.yml
- README.md
- vcsclient/bitbucketcloud.go
- vcsclient/bitbucketcloud_test.go
- vcsclient/bitbucketserver.go
- vcsclient/bitbucketserver_test.go
- vcsclient/common_test.go
- vcsclient/factory.go
- vcsclient/github.go
- vcsclient/github_test.go
- vcsclient/gitlab.go
- vcsclient/gitlab_test.go
- vcsclient/vcsclient.go
- vcsutils/consts.go
- vcsutils/utils.go
- vcsutils/utils_test.go
- vcsutils/webhookparser/bitbucketcloud.go
- vcsutils/webhookparser/bitbucketcloud_test.go
- vcsutils/webhookparser/bitbucketserver.go
- vcsutils/webhookparser/bitbucketserver_test.go
- vcsutils/webhookparser/github.go
- vcsutils/webhookparser/github_test.go
- vcsutils/webhookparser/gitlab.go
- vcsutils/webhookparser/gitlab_test.go
- vcsutils/webhookparser/webhookparser.go
* Scan code with static check
* Add [Go report card](https://goreportcard.com/report/github.com/jfrog/froggit-go) badge
* Improve golint and ineffassign status.
> Add staticcheck

- vcsclient/github.go
> Fix branch name issue for GitHub sarif upload

- README.md
- vcsclient/azurerepos.go
- vcsclient/bitbucketcloud.go
- vcsclient/bitbucketserver.go
- vcsclient/factory.go
- vcsclient/factory_test.go
- vcsclient/github.go
- vcsclient/gitlab.go
- vcsclient/logger.go
> Add Logger and logs

- vcsclient/github.go
- vcsclient/gitlab.go
> Need to check 404 status code before error

- vcsclient/azurerepos.go
> Fix Azure Devops Server remote details

- .github/workflows/cla.yml
> Update CLA assistant

- vcsclient/vcsclient.go
> Fix documentation in vcsclient.go

- README.md
> Update DownloadFileFromRepo docs

- .github/workflows/frogbot-scan-and-fix.yml
- go.mod
> Update frogbot workflow & Go to 1.20.x

- .github/workflows/frogbot-scan-pr.yml
- .github/workflows/test.yml
> Update test workflows to go 1.20

- README.md
- vcsclient/azurerepos.go
- vcsclient/azurerepos_test.go
- vcsclient/bitbucketcloud.go
- vcsclient/bitbucketcloud_test.go
- vcsclient/bitbucketserver.go
- vcsclient/bitbucketserver_test.go
- vcsclient/github.go
- vcsclient/github_test.go
- vcsclient/gitlab.go
- vcsclient/gitlab_test.go
- vcsclient/testdata/bitbucketcloud/pull_requests_list_response.json
- vcsclient/testdata/bitbucketserver/pull_requests_list_response.json
- vcsclient/testdata/github/pull_requests_list_response.json
- vcsclient/testdata/gitlab/pull_requests_list_response.json
- vcsclient/vcsclient.go
---
- Add the pull request description/body to the pull request information in ListOpenPullRequests API.
> Add pull request body to ListOpenPullRequests

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
> Update GetCommits docs

- vcsclient/github.go
- vcsclient/github_test.go
- vcsclient/testdata/github/pull_requests_list_response.json
> Fix wrong GitHub pull request ID

- vcsclient/azurerepos.go
- vcsclient/azurerepos_test.go
- vcsclient/bitbucketcloud.go
- vcsclient/bitbucketcloud_test.go
- vcsclient/bitbucketserver.go
- vcsclient/bitbucketserver_test.go
- vcsclient/github.go
- vcsclient/github_test.go
- vcsclient/gitlab.go
- vcsclient/gitlab_test.go
- vcsclient/vcsclient.go
- vcsutils/utils.go
- vcsutils/utils_test.go
> Add GetGitRemoteURL

- README.md
- vcsclient/azurerepos.go
- vcsclient/azurerepos_test.go
- vcsclient/bitbucketcloud.go
- vcsclient/bitbucketcloud_test.go
- vcsclient/bitbucketcommon.go
- vcsclient/bitbucketserver.go
- vcsclient/bitbucketserver_test.go
- vcsclient/github.go
- vcsclient/github_test.go
- vcsclient/gitlab.go
- vcsclient/gitlab_test.go
- vcsclient/testdata/gitlab/merge_request_changes.json
- vcsclient/testdata/gitlab/merge_request_diff_versions.json
- vcsclient/testdata/gitlab/merge_request_discussion_items.json
- vcsclient/testdata/gitlab/new_merge_request_thread.json
- vcsclient/vcsclient.go
- vcsutils/consts.go
- vcsutils/utils.go
- vcsutils/utils_test.go
> Code Review Comments API

- vcsclient/github.go
- vcsclient/github_test.go
> Fix GitHub ListPullRequestReviews

- vcsclient/azurerepos.go
- vcsutils/utils.go
- vcsutils/utils_test.go
> Azure - omit empty values in UpdatePullRequest

- vcsclient/azurerepos.go
- vcsclient/azurerepos_test.go
- vcsclient/bitbucketcloud.go
- vcsclient/bitbucketcloud_test.go
- vcsclient/bitbucketserver.go
- vcsclient/bitbucketserver_test.go
- vcsclient/github.go
- vcsclient/github_test.go
- vcsclient/gitlab.go
- vcsclient/gitlab_test.go
- vcsclient/vcsclient.go
---
Adding the PR's author to pull request details.
> Add author to pull request details

- README.md
- vcsclient/azurerepos.go
- vcsclient/bitbucketcloud.go
- vcsclient/bitbucketcommon.go
- vcsclient/bitbucketserver.go
- vcsclient/github.go
- vcsclient/github_test.go
- vcsclient/gitlab.go
- vcsclient/gitlabcommon.go
- vcsclient/vcsclient.go
> add CreateOrgVariable method
